### ISSUE TITLE
NODE - Level Check

### ISSUE THREAD

**Issue by sbenemerito** [hugh-n/JF-Learning#109]
**Dependent on Admin-Role**

### Tasks
**1) Create model/table for Level Check**

Name: level_check_results
Fields:
- id : PK, integer
- student_id : FK, integer (Relation with Student table)
- vocabulary : string
- pronunciation : string
- style : string
- composition : string
- comprehension : string
- fluency : string
- created_at : timestamp
- updated_at : timestamp

**2) Level Check API (/levels)**
Format: `<route> <request method> <who can access> <description>`

- [x] /student/:student_id	 (GET, all authenticated) -> Find all for student 
- [x] /:check_id (GET, all authenticated) -> Find one level check
- [x] /create (POST, Jellyfish or role: 1) -> Create a level check

```
student_id
vocabulary
pronunciation
style
composition
comprehension
fluency
```

- [x] /edit/:check_id (PATCH, Jellyfish or role: 1) -> Edit specific level check

```
vocabulary
pronunciation
style
composition
comprehension
fluency
```

**3) Create Dummy data**
Dummy data + seeder

Database reference: [DATABASE ALPHA 1](https://drive.google.com/drive/folders/1BbwE9_I-d7xjxT9lNEzFUWxw3GhOmGoS)
Routing reference: [Alpha Function Checklist 20190528 - Endpoint Status sheet](https://drive.google.com/drive/folders/1O3nW4HVi3jDRGt4l5-e0EkowVWdkfUBO)
