### ISSUE TITLE
NODE - Admin Roles

### ISSUE THREAD

**Issue by sbenemerito** [hugh-n/JF-Learning#110]
**Instead of using the `type` field, make a new table for `roles` and have a `role_id` foreign key field referencing that the role table in Admin**

### Tasks
**1) Create model/table for Roles**

Name: Roles
Fields:
- id : PK, integer
- name : string
- created_at : timestamp
- updated_at : timestamp

**2) Create initial roles seed**
1) Jellyfish
2) Teacher
3) Motivator

**3) Modify Admin model/table**
Modify admin so we have a foreign key field `roles_id` instead of `type` field

**4) Modify Admin seed**
Modify admin seed so we have each type of admin

**5) Admin API modifications**
- [x] Add endpoint: /role/:role_id (GET, Jellyfish) -> Find All With Role
- [x] Add field in /create endpoint: Take `role_id` data instead of type
- [x] Add field in /edit/:admin_id endpoint: Take `role_id` data instead of type

Database reference: [DATABASE ALPHA 1](https://drive.google.com/drive/folders/1BbwE9_I-d7xjxT9lNEzFUWxw3GhOmGoS)
Routing reference: [Alpha Function Checklist 20190528 - Endpoint Status sheet](https://drive.google.com/drive/folders/1O3nW4HVi3jDRGt4l5-e0EkowVWdkfUBO)
