### ISSUE TITLE
NODE - Database structure changes

### ISSUE THREAD

**Issue by sbenemerito** [hugh-n/JF-Learning#179]
**Question**

- [x] Remove table

**Activity**

- [x] question_id -> unit_id (ForeignKey to Unit now)
- [x] Add activity_type field

**Unit**

- [x] id (int, PK) field -> id (varchar, UNIQUE, PK) **will be user inputted**
- [x] title -> name (rename)
- [x] unit_type -> subject_type (rename)
- [x] Remove question_ids

**Task**

- [x] Remove unit_id relationship and field
- [x] New unit_ids field (like [1, 2, 3, 4])

**Content**

- [x] id (int, PK) field -> id (varchar, UNIQUE, PK) **will be user inputted**
- [x] Languages should now be in kana (instead of en, vn -> 英語, ベトナム語)
- [x] New unit_id field, FK to Unit
- [x] Remove audio_url and image_url fields

**QAContent**

- [x] id (int, PK) field -> id (varchar, UNIQUE, PK) **will be user inputted**
- [x] New unit_id field, FK to Unit

<hr/>

- [x] Create static JSON file to be used for determining what learn types exist in each subject_type

```
語彙 -> ["カード(FJ)", "例文", "テスト"]
作文 -> ["カード(FK)", "Shadowing(作文)"]
スピードQA -> ["カード(JJ)"]
スピーチ -> ["スピーチ"]
ロールプレイ -> ["カード(JJ)", "Shadowing(ロールプレイ)"]
```

**Note:** File will be inputted with the proper file name already, just upload in proper folder structure (based on learn_type sheet)
