### ISSUE TITLE
NODE - Resource API updates

### ISSUE THREAD

**Issue by sbenemerito** [hugh-n/JF-Learning#181]
**Question**
- [ ] Remove all API endpoints and routes (models too, if it's still there)

**Content**
- [ ] Accept `id` field in CREATE and UPDATE (string, required in CREATE)
- [ ] Accept `unit_id` field in CREATE and UPDATE (int, required in CREATE)
- [ ] Update file uploading 

**Task**
- [ ] Don't accept `unit_id` anymore
- [ ] Accept `unit_ids` in CREATE and UPDATE (JSON, required in CREATE. Make sure to JSON.parse() input)

**Unit**
- [ ] Accept `id` field in CREATE and UPDATE (string, required in CREATE)
- [ ] Don't accept `question_ids` anymore
- [ ] Don't accept `title` anymore, but accept `name` (probably just rename)
